# .air.toml - Hot reload configuration for Storage Control Plane
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/storage-control-plane.exe ."
  bin = "tmp/storage-control-plane.exe"
  include_ext = ["go", "env"]
  exclude_dir = ["tmp", ".git", ".backup", "vendor"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  delay = 1000
  log = "build-errors.log"
  send_interrupt = true
  kill_delay = 2000

[log]
  color = "true"
  timestamp = "true"

[screen]
  clear_on_rebuild = true
  keep_scroll = false
